<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<DefineConstants>$(DefineConstants);IL2CPP</DefineConstants>
		<Configurations>Debug;Release;</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="$(Configuration.Contains('Debug'))">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>portable</DebugType>
		<Optimize>false</Optimize>
		<DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="$(Configuration.Contains('Release'))">
		<DebugType>none</DebugType>
		<Optimize>true</Optimize>
		<DefineConstants>$(DefineConstants);TRACE</DefineConstants>
	</PropertyGroup>
	
	<Target Name="PostBuild" AfterTargets="Build">
		<Copy SourceFiles="$(TargetDir)$(TargetFileName)" DestinationFolder="C:\Program Files (x86)\Steam\steamapps\common\Schedule I\Mods\" OverwriteReadOnlyFiles="true" />
	</Target>
	
	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<LangVersion>default</LangVersion>
		<TargetFramework>net6.0</TargetFramework>

		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<Version>1.0.0</Version>
		<Product>Flatline</Product>
		<Company>XOWithSauce</Company>
		<Copyright>Copyright XOWithSauce 2026 Source MIT</Copyright>

		<Authors>XOWithSauce</Authors>
		<Description>Schedule I Flatline Mod</Description>
		<RepositoryUrl>https://github.com/XOWithSauce/schedule-flatline</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<NeutralLanguage>en-US</NeutralLanguage>

		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<OutputType>Library</OutputType>

		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<WarningsAsErrors></WarningsAsErrors>
		<NoWarn></NoWarn>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="LavaGang.MelonLoader" Version="0.7.1" />
		<PackageReference Include="Lib.Harmony" Version="2.4.2" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\Source\**\*.cs" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Assembly-CSharp">
			<HintPath>libs-il2cpp\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cppmscorlib">
			<HintPath>libs-il2cpp\Il2Cppmscorlib.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppFishNet.Runtime">
			<HintPath>libs-il2cpp\Il2CppFishNet.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppInterop.Runtime">
			<HintPath>libs-il2cpp\Il2CppInterop.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>libs-il2cpp\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AnimationModule">
			<HintPath>libs-il2cpp\UnityEngine.AnimationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AIModule">
			<HintPath>libs-il2cpp\UnityEngine.AIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>libs-il2cpp\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>libs-il2cpp\UnityEngine.UI.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIModule">
			<HintPath>libs-il2cpp\UnityEngine.UIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
			<HintPath>libs-il2cpp\UnityEngine.PhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
			<HintPath>libs-il2cpp\UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
			<HintPath>libs-il2cpp\Unity.TextMeshPro.dll</HintPath>
		</Reference>
		<Reference Include="Unity.InputSystem">
			<HintPath>libs-il2cpp\Unity.InputSystem.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputModule">
			<HintPath>libs-il2cpp\UnityEngine.InputModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
			<HintPath>libs-il2cpp\UnityEngine.InputLegacyModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ImageConversionModule">
			<HintPath>libs-il2cpp\UnityEngine.ImageConversionModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AudioModule">
			<HintPath>libs-il2cpp\UnityEngine.AudioModule.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cpp">
			<HintPath>libs-il2cpp\Il2Cpp.dll</HintPath>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<HintPath>libs-il2cpp\Newtonsoft.Json.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>